import { OnInit, ElementRef, AfterViewInit, OnDestroy } from '@angular/core';
import { Observable, Subscription } from 'rxjs';
import { VgApiService, VgControlsHiddenService } from '@videogular/ngx-videogular/core';
export declare class VgControlsComponent implements OnInit, AfterViewInit, OnDestroy {
    private API;
    private hidden;
    elem: HTMLElement;
    target: any;
    isAdsPlaying: string;
    hideControls: boolean;
    vgFor: string;
    vgAutohide: boolean;
    vgAutohideTime: number;
    private timer;
    mouseMove$: Observable<any>;
    touchStart$: Observable<any>;
    subscriptions: Subscription[];
    constructor(API: VgApiService, ref: ElementRef, hidden: VgControlsHiddenService);
    ngOnInit(): void;
    onPlayerReady(): void;
    ngAfterViewInit(): void;
    onPlay(): void;
    onPause(): void;
    onStartAds(): void;
    onEndAds(): void;
    hide(): void;
    show(): void;
    private hideAsync;
    ngOnDestroy(): void;
}
